---
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: black-check
        name: Check python files with black
        entry: black
        args: [--check]
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: black-fix
        name: Format python files with black
        entry: black
        language: system
        verbose: true
        stages: [manual]
        types: [python]
  - repo: local
    hooks:
      - id: pylint
        name: Check python files with pylint
        entry: pylint
        language: system
        types: [python]
